server:
  port: 4000
spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:4200"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
      routes:
        - id: student-service
          uri: http://127.0.0.1:4001
          predicates:
            - Path=/api/v1/students/**
          filters:
            - StripPrefix=2
        - id: course-service
          uri: http://127.0.0.1:4002
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - StripPrefix=2
        - id: enrollment-service
          uri: http://127.0.0.1:4003
          predicates:
            - Path=/api/v1/enrollments/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://127.0.0.1:4010
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2
        - id: library-service
          uri: http://127.0.0.1:4005
          predicates:
            - Path=/api/v1/library/**
          filters:
            - StripPrefix=2
        - id: payment-service
          uri: http://127.0.0.1:4004
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=2
        - id: infrastructure-service
          uri: http://127.0.0.1:4006
          predicates:
            - Path=/api/v1/infrastructure/**
          filters:
            - StripPrefix=2

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
